spring:
  datasource:
    url: jdbc:mysql://42.194.216.42:3306/lagou_test
    username: root
    password: L*ofwf7Tr%a1

email:
  account: 664961086@qq.com
  password: thjbsxtibbnibbhb
  smtpHost: smtp.qq.com
  smtpPort: 465

ip:
  restrict:
    count: 2
    timeInterval: 1000 * 60 *1L
